# pytest.ini
[pytest]

markers =
    Get_Search_Employee_Data: mark a test for search employee data API
    Get_Employee_Details_test: mark a test for get employee details API
    Get_Work_and_Education_Experience_test: mark a test for get work and education experience API
    Get_Reporting_Manager_Details_test: mark a test for get reporting manager details API
    Get_Employee_Details_test: mark a test for get employee details API
    Get_All_Projects_test: mark a test for get all projects API
    Get_Project_test: mark a test for get project API
    Get_Get_Employee_Certificates_test: mark a test for get employee certificates API
    Get_Employee_Attendance_test: mark a test for get employee attendance API
    Get_Employee_Skill_Data_test: mark a test for get employee skill data API
    Get_Performance_Rating_test: mark a test for get performance rating API
    Get_Project_Details_test: mark a test for get project details API
    Get_Employee_Certificates_test: mark a test for get employee certificates API
    Get_Associates_Under_Manager_test: mark a test for get associates under manager API
